apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::982105689473:role/eksctl-online-boutique-nodegroup-b-NodeInstanceRole-8xWs3zyIJsUe
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::982105689473:role/jenkins-ec2-eks-role
      username: jenkins-ec2-eks-role
      groups:
      - system:masters
