name: Build and Push Docker Images to Amazon ECR Public

on:
  push:
    branches:
      - main

env:
  ECR_REGISTRY: public.ecr.aws/h4l1q1r7
  VERSION: v0.3.7

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and push microservice images
        run: |
          for service in frontend productcatalogservice cartservice adservice checkoutservice currencyservice emailservice paymentservice shippingservice; do
            echo "Building and pushing $service..."
            docker build -t $ECR_REGISTRY/onlineboutique-$service:$VERSION ./src/$service
            docker push $ECR_REGISTRY/onlineboutique-$service:$VERSION
          done
