apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-src
  labels:
    app: cartservice-src
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice-src
  template:
    metadata:
      labels:
        app: cartservice-src
    spec:
      containers:
      - name: cartservice-src
        image: 982105689473.dkr.ecr.us-east-2.amazonaws.com/cartservice-src:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cartservice-src
spec:
  selector:
    app: cartservice-src
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
