apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingassistantservice
  labels:
    app: shoppingassistantservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingassistantservice
  template:
    metadata:
      labels:
        app: shoppingassistantservice
    spec:
      containers:
      - name: shoppingassistantservice
        image: 982105689473.dkr.ecr.us-east-2.amazonaws.com/shoppingassistantservice:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: shoppingassistantservice
spec:
  selector:
    app: shoppingassistantservice
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
